# fly.toml app configuration file generated for edu-bff on 2024-11-09T12:59:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edu-bff'
primary_region = 'gru'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[deploy]
release_command = "npx prisma migrate deploy"

[env]
API_URL = "https://edu-ai.fly.dev"

